[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day1"
path = "day1/day1.rs"

[[bin]]
name = "day2p1"
path = "day2/prob1.rs"

[[bin]]
name = "day2p2"
path = "day2/prob2.rs"

[[bin]]
name = "day5"
path = "day5/day5.rs"


[dependencies]
